name: coinflux
description: "Live Fiat & Crypto Currency Converter"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.3.1
  dio: ^5.4.0
  shared_preferences: ^2.3.0
  intl: ^0.20.2
  flutter_native_splash: ^2.4.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo.jpg"
  min_sdk_android: 21
  adaptive_icon_background: "#4338CA"
  adaptive_icon_foreground: "assets/logo.jpg"

flutter_native_splash:
  color: "#4338CA"
  image: assets/logo.jpg
  color_dark: "#4338CA"
  image_dark: assets/logo.jpg
  android_12:
    image: assets/logo.jpg
    icon_background_color: "#4338CA"
    image_dark: assets/logo.jpg
    icon_background_color_dark: "#4338CA"
  ios: true
  android: true
  web: false

flutter:
  uses-material-design: true
  assets:
    - assets/
